'use strict';

const PDFDocument = require('pdfkit');
const { calculate, formatINR } = require('./cacEngine');
const { drawPaybackChart } = require('./chartVector');

/**
 * Stream a PDF report into the response.
 */
function streamPdfReport(res, inputs, custom) {
  const result = calculate(inputs);

  const doc = new PDFDocument({
    size: 'A4',
    margin: 40,
    info: {
      Title: `${custom.company} — ${custom.title}`,
      Author: custom.founder,
      Subject: 'Customer Acquisition Report'
    }
  });

  doc.pipe(res);

  const PAGE_W = doc.page.width - 80; // usable width

  /* ---------- header banner ---------- */
  doc.rect(40, 40, PAGE_W, 60).fill('#D4A843');
  doc.fillColor('#080B12')
     .fontSize(16).font('Helvetica-Bold')
     .text(`${custom.company} — ${custom.title}`, 52, 56, { width: PAGE_W - 24 });
  doc.fontSize(9).font('Helvetica')
     .text(custom.tagline, 52, 78, { width: PAGE_W - 24 });

  doc.moveDown(4);

  /* ---------- meta ---------- */
  const now = new Date();
  doc.fillColor('#4B5563').fontSize(8).font('Helvetica');
  doc.text(
    `Report Date: ${now.toLocaleDateString('en-IN')} at ${now.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}`,
    40, doc.y
  );
  doc.text(`Mode: ${result.mode.toUpperCase()}`, 40, doc.y, { align: 'right', width: PAGE_W });

  doc.moveDown(1.2);

  /* ---------- summary ---------- */
  sectionTitle(doc, '1. Summary');
  kv(doc, 'Total Acquisition Spend', formatINR(result.inputs.spend), PAGE_W);
  kv(doc, 'New Customers Acquired', result.inputs.customers.toLocaleString('en-IN'), PAGE_W);
  kv(doc, 'Customer Acquisition Cost (CAC)', formatINR(result.cac), PAGE_W, '#6D28D9');
  kv(doc, 'Lifetime Value (LTV)', formatINR(result.ltv), PAGE_W, '#047857');
  kv(doc, 'LTV : CAC Ratio', result.ltvCac.toFixed(2) + '×', PAGE_W);
  kv(doc, 'CAC Payback', Number.isFinite(result.paybackMonths)
      ? result.paybackMonths.toFixed(2) + ' months'
      : '—', PAGE_W);
  kv(doc, 'Net Profit per Customer',
     (result.netProfitPerCustomer >= 0 ? '+' : '') + formatINR(result.netProfitPerCustomer),
     PAGE_W, '#B45309');

  doc.moveDown(1.5);

  /* ---------- chart ---------- */
  if (custom.chart && result.monthRows.length > 1) {
    sectionTitle(doc, '2. Month-wise CAC Payback');
    drawPaybackChart(doc, result.monthRows, {
      x: 40, y: doc.y + 24, width: PAGE_W, height: 200,
      formatShort: (n) => {
        const v = Math.round(n);
        if (v >= 100000) return '₹' + (v / 100000).toFixed(1) + 'L';
        if (v >= 1000)   return '₹' + (v / 1000).toFixed(0) + 'K';
        return '₹' + v;
      }
    });
    doc.y += 240;
  }

  /* ---------- channel benchmarks ---------- */
  if (custom.ref) {
    doc.addPage();
    sectionTitle(doc, '3. Channel CAC Benchmarks');

    const cols = ['Channel', 'Index', 'Est. CAC', 'Customers', 'LTV:CAC'];
    const colW = [200, 50, 90, 80, 60];
    let cy = doc.y + 6;

    // header
    doc.fontSize(8).font('Helvetica-Bold').fillColor('#92400E');
    let cx = 40;
    cols.forEach((c, i) => {
      doc.text(c, cx + 4, cy, { width: colW[i] - 8 });
      cx += colW[i];
    });
    cy += 14;

    doc.font('Helvetica').fillColor('#374151');
    result.channels.forEach(ch => {
      cx = 40;
      const row = [
        ch.name, ch.index.toFixed(2) + '×',
        formatINR(ch.cac), Math.round(ch.customers).toLocaleString('en-IN'),
        ch.ltvCac.toFixed(2) + '×'
      ];
      row.forEach((v, i) => {
        doc.fillColor(i === 4 ? (ch.healthy ? '#047857' : '#B91C1C') : '#374151');
        doc.text(v, cx + 4, cy, { width: colW[i] - 8 });
        cx += colW[i];
      });
      cy += 13;
    });
  }

  /* ---------- disclaimer ---------- */
  if (custom.disclaimer) {
    doc.moveDown(2);
    sectionTitle(doc, '4. Disclaimer');
    doc.fontSize(7.5).font('Helvetica').fillColor('#7F1D1D')
       .text(
         `This report is generated by ${custom.company} for educational purposes. ` +
         'It assumes constant churn and margin. Channel indices are illustrative. ' +
         'Consult a qualified adviser before making investment decisions.',
         40, doc.y, { width: PAGE_W }
       );
  }

  /* ---------- footer ---------- */
  doc.moveDown(2);
  doc.fontSize(8).fillColor('#6B7280').text(
    `${custom.company} · ${custom.tagline} · Founded by ${custom.founder}`,
    40, doc.y, { width: PAGE_W, align: 'center' }
  );

  doc.end();
}

/* ---------- small helpers ---------- */

function sectionTitle(doc, text) {
  doc.moveDown(0.5);
  doc.fontSize(12).font('Helvetica-Bold').fillColor('#B45309').text(text);
  doc.moveTo(40, doc.y + 2)
     .lineTo(doc.page.width - 40, doc.y + 2)
     .lineWidth(1.2).strokeColor('#D4A843').stroke();
  doc.moveDown(0.8);
}

function kv(doc, key, value, width, valueColor) {
  const y = doc.y;
  doc.fontSize(9).font('Helvetica-Bold').fillColor('#374151')
     .text(key, 40, y, { width: width * 0.55 });
  doc.font('Helvetica').fillColor(valueColor || '#111827')
     .text(value, 40 + width * 0.55, y, { width: width * 0.45, align: 'right' });
  doc.moveDown(0.4);
}

module.exports = { streamPdfReport };